import lookup from "country-code-lookup";
import { getStatistics } from "@/actions/statisticsActions";

export const metadata: Metadata = {
  title: "Statistics",
  description: "Generated by create next app",
};

export default async function page() {
  const mostSearchedCities = await getStatistics();
  return (
    <>
      <h1 className="text-center text-3xl">Statistics</h1>
      {mostSearchedCities && mostSearchedCities?.length > 2 && (
        <h3 className="my-4 text-center text-xl">
          Top {mostSearchedCities?.length} cities by search:
        </h3>
      )}
      <ul className="mx-auto flex max-w-[300px] flex-col divide-y-2">
        {mostSearchedCities &&
          mostSearchedCities.map((city) => {
            const countryName = lookup.byIso(city.country);
            return (
              <li key={city.id}>
                <span className="font-bold">{city.name}</span>,{" "}
                {countryName?.country}
                <br />
                Search count: {city.searchCount}
              </li>
            );
          })}
      </ul>
    </>
  );
}
